# Generated by Django 5.0.2 on 2024-02-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                (
                    'id',
                 models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                 )
                ),
                (
                    'name',
                    models.CharField(max_length=30, verbose_name='Название автомобиля')
                ),
            ],
        ),
    ]
